[pytest]

; Где искать тесты (по умолчанию — текущая папка)
testpaths = tests

; Какие файлы считать тестовыми
python_files = test_*.py *_test.py

; Какие функции считать тестами
python_functions = test_*

; Какие классы считать тестовыми
python_classes = Test*

; Флаги по умолчанию при каждом запуске pytest
; -v = подробный вывод, -ra = показывать причины skip/xfail
addopts = -v -ra

; Чтобы pytest видел src/ как пакет
pythonpath = .

asyncio_mode = auto